[package]
name = "bulk-test2"
version = "0.1.0"
edition = "2024"

[dependencies]
nusb = "0.1.14"
#nusb = "0.2.0-beta"
futures-lite = "1.13.0"
env_logger = "0.10.0"
hex-literal = "1.0.0"

#[[bin]]
#name = "main"